version: '3'

# Declare services
services:
  traefik:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${SERVER_NGINX_CERTS_DIR}:/letsencrypt
    command:
      # - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entryPoints.web.http.redirections.entryPoint.to = "websecure"
      - --entryPoints.web.http.redirections.entryPoint.scheme = "https"
      - --certificatesResolvers.lets-encrypt.acme.email=${LETSENCRYPT_DEFAULT_EMAIL}
      - --certificatesResolvers.lets-encrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesResolvers.lets-encrypt.acme.tlschallenge=true
    # labels:
      # - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      # - "traefik.http.routers.http-catchall.entrypoints=web"
      # - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      # - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  whalecoiner:
    environment:
      # - VIRTUAL_HOST=whalecoiner.com,sonniesedge.net,sonnieseedge.co.uk,www.whalecoiner.com,www.sonniesedge.net,www.sonnieseedge.co.uk,beta.whalecoiner.com
      # - LETSENCRYPT_HOST=whalecoiner.com,sonniesedge.net,sonnieseedge.co.uk,www.whalecoiner.com,www.sonniesedge.net,www.sonnieseedge.co.uk,beta.whalecoiner.com
      - NODE_ENV=production
    volumes:
      - ${SERVER_CONTENT_DIR}:${APP_CONTENT_DIR}
      - ${SERVER_LOG_DIR}:${APP_LOG_DIR}
      - ${SERVER_DATA_DIR}:${APP_DATA_DIR}
    command: ["npm", "start"]
    networks:
      - internal
      - web
    labels:
      # - "traefik.port=80"
      - "traefik.http.routers.whalecoiner.rule=Host(`beta.whalecoiner.com`)"
      - "traefik.http.routers.whalecoiner.tls=true"
      - "traefik.http.routers.whalecoiner.tls.certresolver=lets-encrypt"
      - "traefik.http.routers.whalecoiner.entrypoints=websecure"

  # nginx: # Add nginx volumes for production
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ${SERVER_NGINX_CERTS_DIR}:/etc/nginx/certs
  #     - ${SERVER_NGINX_VHOSTS_DIR}:/etc/nginx/vhost.d
  #     - ${SERVER_NGINX_HTML_DIR}:/usr/share/nginx/html # Used for certificate creation, not content
  # nginx-proxy-acme: # Add certificate handler for production
  #   image: nginxproxy/acme-companion
  #   volumes_from: 
  #     - nginx
  #   volumes:
  #     - acme:/etc/acme.sh
  #     - /var/run/docker.sock:/var/run/docker.sock:ro # Binding the host docker socket (/var/run/docker.sock) inside the container to /var/run/docker.sock is a requirement of nginxproxy/acme-companion.
  #   environment:
  #     - DEFAULT_EMAIL=${LETSENCRYPT_DEFAULT_EMAIL}
