version: '3'

# Declare volumes
volumes:
  nodemodules:
networks:
  web:
    external: true
  internal:
    external: false

# Declare services
services:
  whalecoiner:
    build: .
    volumes:
      - nodemodules:/usr/src/app/node_modules
    expose:
      - "3000"
  # redis:
  #   image: "redis:alpine"

  traefik:
    image: "traefik:v2.2.0"
    command:
      - --entrypoints.web.address=:80
      - --providers.docker=true
      - --providers.docker.network=web
    #   - --api.insecure 
    labels:
      - "traefik.http.services.whalecoiner.loadbalancer.server.port=3000"
    ports:
      - "80:80"
      # - "8080:8080"
    networks:
      - web
    container_name: traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
