version: '3'

services:
  indieweb-express-site:
    volumes:
      - ./:/usr/src/app
    command: ["npm", "run", "dev"]
    environment:
      - VIRTUAL_HOST=whalecoiner.localhost
      - VIRTUAL_PORT=3000
      - NODE_ENV=development
