version: '3'

# Declare volumes
volumes:
  acme:

# Declare services
services:
  indieweb-express-site:
    environment:
      # - VIRTUAL_HOST=whalecoiner.com,sonniesedge.net,sonnieseedge.co.uk,www.whalecoiner.com,www.sonniesedge.net,www.sonnieseedge.co.uk,beta.whalecoiner.com
      - VIRTUAL_HOST=beta.whalecoiner.com
      - LETSENCRYPT_HOST=beta.whalecoiner.com
      - VIRTUAL_PORT=3000
    command: ["npm", "start"]
  nginx-proxy: # Add nginx volumes for production
    volumes:
      - ${NGINX_CERTS_DIR}:/etc/nginx/certs
      - ${NGINX_VHOST_DIR}:/etc/nginx/vhost.d
      - ${NGINX_HTML_DIR}:/usr/share/nginx/html
  nginx-proxy-acme: # Add certificate handler for production
    image: nginxproxy/acme-companion
    volumes_from: 
      - nginx-proxy
    volumes:
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=${NGINX_DEFAULT_EMAIL}
