
# Declare volumes
volumes:
  certs:
  vhost:
  html:
  acme:

# Declare services
services:
  indieweb-express-site:
    environment:
      # - VIRTUAL_HOST=whalecoiner.com,sonniesedge.net,sonnieseedge.co.uk,www.whalecoiner.com,www.sonniesedge.net,www.sonnieseedge.co.uk,beta.whalecoiner.com
      - VIRTUAL_HOST=beta.whalecoiner.com
      - LETSENCRYPT_HOST=beta.whalecoiner.com
      - VIRTUAL_PORT=3000
  nginx-proxy: # Add volumes for production
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      # - /path/to/certificates:/etc/nginx/certs
  nginx-proxy-acme: # Add certificate handler for production
    image: nginxproxy/acme-companion
    deploy:
      restart_policy:
        condition: always
    volumes_from: 
      - nginx-proxy
    volumes:
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=letsencrypt@whalecoiner.com
