version: '3'

# Declare volumes
volumes:
  nodemodules:

# Declare services
services:
  indieweb-express-site:
    build: .
    volumes:
      - nodemodules:/usr/src/app/node_modules
    expose:
      - "3000"
  redis:
    image: "redis:alpine"
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro # Binding the host docker socket (/var/run/docker.sock) inside the container to /tmp/docker.sock is a requirement of nginx-proxy.
