version: '3'

# Declare volumes
volumes:
  acme:
  vhosts:
  html:
  certs:
  content:
    external: true

# Declare services
services:
  indieweb-express-site:
    environment:
      - VIRTUAL_HOST=whalecoiner.com,sonniesedge.net,sonnieseedge.co.uk,www.whalecoiner.com,www.sonniesedge.net,www.sonnieseedge.co.uk,beta.whalecoiner.com
      - LETSENCRYPT_HOST=whalecoiner.com,sonniesedge.net,sonnieseedge.co.uk,www.whalecoiner.com,www.sonniesedge.net,www.sonnieseedge.co.uk,beta.whalecoiner.com
      - VIRTUAL_PORT=3000
      - NODE_ENV=production
    volumes:
      - content:/usr/src/content
    command: ["npm", "start"]
  nginx-proxy: # Add nginx volumes for production
    volumes:
      - certs:/etc/nginx/certs
      - vhosts:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html # User for certificate creation, not content
  nginx-proxy-acme: # Add certificate handler for production
    image: nginxproxy/acme-companion
    volumes_from: 
      - nginx-proxy
    volumes:
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro # Binding the host docker socket (/var/run/docker.sock) inside the container to /var/run/docker.sock is a requirement of nginxproxy/acme-companion.
    environment:
      - DEFAULT_EMAIL=${NGINX_DEFAULT_EMAIL}
