version: '3'

# Declare volumes
volumes:
  nodemodules:

# Declare services
services:
  indieweb-express-site:
    build: .
    volumes:
      - nodemodules:/usr/src/app/node_modules
    expose:
      - "3000"
  redis:
    image: "redis:alpine"
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"

  docker-gen:
    image: jwilder/docker-gen 
    volumes_from: 
      - nginx
    volumes: 
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - $(pwd):/etc/docker-gen/templates
    command: "-notify-sighup nginx -watch -only-exposed /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"
