# This workflow will do a clean install of node dependencies, build the source code and run tests.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI tests and deployment

on:
  push:
    branches: [ master, debug ]

env:
  APPDIR: ${{ secrets.SERVER_DIR }}
  NODE_VERSION: 14.15.0

jobs:
  # Job 1: Test the app
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from ${{ github.repository }}
      uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1.4.4
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install app dependencies
      run: npm ci
    - name: Run app tests
      run: npm test

  # Job 2: Deploy the app
  deploy-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from ${{ github.repository }}
      uses: actions/checkout@v2
    - name: Create .env file
      run: 'touch .env'
      shell: bash
    - name: Write environment secrets to app .env file
      run: 
        'echo "DATA_DIR=$DATA_DIR" >> .env'
        'echo "CONTENT_DIR=$CONTENT_DIR" >> .env'
        'echo "TWITTER_CONSUMER_KEY=$TWITTER_CONSUMER_KEY" >> .env'
        'echo "TWITTER_CONSUMER_SECRET=$TWITTER_CONSUMER_SECRET" >> .env'
      shell: bash
    - name: Copy app to remote server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        ARGS: "-rltz --delete --exclude '.git/' --exclude '.github/' --exclude 'node_modules/' --stats"
        REMOTE_HOST: ${{ secrets.SERVER_IP }}
        REMOTE_USER: ${{ secrets.SERVER_USER }}
        TARGET: ${{ secrets.SERVER_DIR }}
    - name: Execute build script on remote server. Builds npm and runs pm2.
      uses: appleboy/ssh-action@master        
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: ${{ secrets.SERVER_DIR }}/build.sh ${{ env.APPDIR }}
