# This workflow will do a clean install of node dependencies, build the source code and run tests.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master, debug ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 14.15.0
      APPDIR: ${{ secrets.SERVER_DIR }}

    steps:
    - name: Checkout code from ${{ github.repository }}
      uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1.4.4
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install app dependencies
      run: npm ci
    - name: Run app tests
      run: npm test
    - name: Copy app to remote server
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          ARGS: "-rltz --delete --exclude '.git/' --exclude '.github/' --exclude 'node_modules/' --stats"
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          TARGET: ${{ secrets.SERVER_DIR }}
    - name: Execute build script on remote server
      uses: appleboy/ssh-action@master        
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: ${{ secrets.SERVER_DIR }}/build.sh ${{ env.APPDIR }}
